<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';
require_once __DIR__ . '/oss-sdk/autoload.php';

return ComposerAutoloaderInit9c4ae0f1e3be1063039c0f96f3fd7424::getLoader();
